### ISSUE TITLE
Is this plugin still maintained? 

### ISSUE THREAD

**Issue by Olian04** [mathiasfrohlich/vscode-kotlin#15]
The last commit to master was in July and there are multiple PR from over 2 months ago open with no comments... So my question stands, is this plugin still maintained? 
If not the repository should probably be marked as deprecated.

**Comment by mathiasfrohlich** [comment]
Hey @Olian04 

I really appreciate your interest in the project.
Have been away for some time and lacked time for open source projects.
I will make sure to speed things up.

If you would, i could add you as a collaborator and help manage this repo ?
In that case will manage the publishing of changes to the market place.
