### ISSUE TITLE
Support Kotlin Debugging

### ISSUE THREAD

**Issue by fractalic** [mathiasfrohlich/vscode-kotlin#19]
I'm not able to set breakpoints in Kotlin files within vs code, possibly because this extension does not yet support Kotlin debugging

**Comment by nishtahir** [comment]
The extension currently doesn't support this. Adding debug capabilities is something I've been thinking about, but is a non-trivial feature to add. 🤔 

I'm open to ideas for implementing something like this, if there's enough interest.

**Comment by fwcd** [comment]
@nishtahir I am currently implementing Kotlin debugging for VSCode, in case anyone is interested: https://github.com/fwcd/KotlinDebugAdapter

**Comment by nishtahir** [comment]
Looks like we'll leave this feature to the project above and just focus on proper syntax highlighting.
