### ISSUE TITLE
End of line comments not always syntax highlighted

### ISSUE THREAD

**Issue by cj81499** [mathiasfrohlich/vscode-kotlin#25]
![image](https://user-images.githubusercontent.com/9152032/39979435-5746e2e8-5714-11e8-82c1-0c87d53cfde0.png)

As shown in the image, some comments are missed by the syntax highlighter.

EDIT: changed image to include a properly highlighted comment for comparison.

**Comment by 3dformortals** [comment]
have same behavior ... and too after `array.set()` syntax
![screenshot_20180919_200131](https://user-images.githubusercontent.com/17385953/45768940-d9a4f800-bc46-11e8-9980-0f8315dd3ba4.png)

**Comment by nishtahir** [comment]
I believe that this has been resolved in the latest release.

**Comment by cj81499** [comment]
Can confirm that the newest version fixed the example I gave! Thanks.
