### ISSUE TITLE
Add support for Kotlin-JS

### ISSUE THREAD

**Issue by tomschrot** [mathiasfrohlich/vscode-kotlin#28]
Hi
I develop online apps and find VSC a great tool.
For all the client (browser) code I use Kotlin-JS but the plugin keeps complaining about unresolved references (like in e.g. import org.w3c.dom.* ) or unsupported context (like dynamic)  although the compiler runs through without problems. Can you please complete these references, or give advise for configuring the plugin!?

thx

**Comment by nishtahir** [comment]
Unfortunately, I think you're reporting to the wrong project
I think you mean to report your issue to https://github.com/fwcd/KotlinLanguageServer
