### ISSUE TITLE
Kotlin icon does not display for Kotlin scripts (files with *.kts extension)

### ISSUE THREAD

**Issue by TAGC** [mathiasfrohlich/vscode-kotlin#29]
In VS Code, the extension provides a nice looking icon for regular Kotlin files (*.kt) but not for Kotlin script files (*.kts).

![code_2018-10-15_07-57-12](https://user-images.githubusercontent.com/1588951/46937184-772df480-d058-11e8-87dc-c615cd2980f8.png)

It would be nice if the icon were used for Kotlin scripts as well.

**Comment by fwcd** [comment]
@TAGC Your file icon theme is reponsible for the icons, so you might want to report the issue there. Just as a side note, I have [added Kotlin icons for `.kt` and `.kts` files](https://github.com/jesseweed/seti-ui/pull/502) to the [Seti UI theme](https://github.com/jesseweed/seti-ui), which is the default icon theme in VSCode:

![image](https://user-images.githubusercontent.com/30873659/47579801-5d8c8700-d94d-11e8-9e1a-2e1026a8f1ce.png)

With Seti, both `.kt` and `.kts` files will be highlighted:

![image](https://user-images.githubusercontent.com/30873659/47579863-814fcd00-d94d-11e8-905d-361ca4660364.png)

**Comment by nishtahir** [comment]
Neat! Thanks for looking into this.
