### ISSUE TITLE
Support for annotations

### ISSUE THREAD

**Issue by Jonatino** [mathiasfrohlich/vscode-kotlin#3]
Could we get syntax highlighting for things like @JvmStatic, @JvmField, @Throws annotations? 

https://dl.dropboxusercontent.com/u/91292881/ShareX/2016/12/Code%20-%20Insiders_2016-12-03_22-41-27.png

**Comment by nishtahir** [comment]
I've begun working on support for this as of  ee5f83c

**Comment by nishtahir** [comment]
This has been fixed as of the 1.6.0 release.
