### ISSUE TITLE
Tabs for indentation

### ISSUE THREAD

**Issue by kmansoft** [mathiasfrohlich/vscode-kotlin#32]
Hi,

Is there a way to get tabs (4 characters wide, not spaces) when using your extension?

That's my personal preference even if it's not Kotlin's official style.

I tried this in VS Code settings JSON file but it seemingly did nothing... Still getting 2 spaces for each Tab press.

```
"[kotlin]": {
	"editor.tabSize": 4,
},
```

**Comment by fwcd** [comment]
AFAIK, that is unrelated to this extension as VSCode handles the indentation. The following precedence order is used to determine which indentation style should be used:

```
Predominant style in the current text file > Workspace Setting > User Setting
```

The `editor.tabSize` setting is probably not what you want, however. Instead you should set: `editor.insertSpaces` to `false`.

**Comment by kmansoft** [comment]
Thanks, it was the "predominant style" at this point and there is a popup (unrelated to your plugin) to change that.
