### ISSUE TITLE
Markdown Syntax Highlighting

### ISSUE THREAD

**Issue by IvanAtanasov89** [mathiasfrohlich/vscode-kotlin#33]
Hi,

Syntax highlighting in markdown is code blocks is still not working for me. It was supposed to be fixed in #11 

In a markdown document if I place something like this it will not be highlighted:

```kotlin
val len = text?.run {
    println("get length of $this")
    length //`this` can be omitted
} ?: 0
```

Thanks,
Ivan

**Comment by nishtahir** [comment]
Looks like this was a regression after some changes to the grammar. It should be fixed in the next release.
