### ISSUE TITLE
print() highlighting not working

### ISSUE THREAD

**Issue by wildlava** [mathiasfrohlich/vscode-kotlin#36]
The highlighting color of the "println" function works as expected, but the color of "print" does not (it stays white, e.g.). Here's what it looks like:

<img width="781" alt="Screen Shot 2019-04-03 at 11 42 34" src="https://user-images.githubusercontent.com/6426421/55496886-aa177500-5605-11e9-9ba7-b0c045fb066e.png">

**Comment by nishtahir** [comment]
Good catch... I don't think this is listed as a built-in function in the grammar

**Comment by wildlava** [comment]
Yep, you are right! I also found it in the build-in function section. Cool! I just made a pull request...
