### ISSUE TITLE
Customizable colors

### ISSUE THREAD

**Issue by tapz** [mathiasfrohlich/vscode-kotlin#47]
Should be some way to customize the colors. Currently, the syntax highlighting is basically useless as almost everything is in the same color.

<img width="649" alt="Screenshot 2020-06-22 at 13 39 08" src="https://user-images.githubusercontent.com/11726387/85278587-d1b65f80-b48d-11ea-81d0-f437ade2097f.png">

**Comment by tapz** [comment]
Compared to JavaScript syntax highlighting:

<img width="741" alt="Screenshot 2020-06-22 at 13 41 24" src="https://user-images.githubusercontent.com/11726387/85278796-1510ce00-b48e-11ea-9055-1b2d4bae6f25.png">

**Comment by nishtahir** [comment]
The grammar sets scopes for highlighting, but this is ultimately the responsibility of the theme. You are welcome to offer suggestions on scopes that might be helpful but until then there's nothing actionable here.
