### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by Syrikal** [mathiasfrohlich/vscode-kotlin#53]
No syntax errors are highlighted, no matter how blatant. Am I doing something wrong?
![image](https://user-images.githubusercontent.com/76715986/137796538-289afc3a-dca7-4d25-9ea0-3facd325988e.png)

**Comment by nishtahir** [comment]
https://github.com/mathiasfrohlich/vscode-kotlin/issues/21#issuecomment-433481620

As mentioned here. This project does not offer error detection, autocomplete or any typical IDE features. This is just a simple syntax highlighter, nothing more
