### ISSUE TITLE
won't install in devcontainer

### ISSUE THREAD

**Issue by lattice0** [mathiasfrohlich/vscode-kotlin#55]
Why this plugin cannot be installed inside a devcontainer?

**Comment by nishtahir** [comment]
If you are getting some kind of error. It would be helpful to share. However, with no information, I can't offer any feedback

**Comment by lattice0** [comment]
![image](https://user-images.githubusercontent.com/6632321/172258176-fd95c51a-bdf3-4fda-91df-6763c4c7a0b5.png)
![image](https://user-images.githubusercontent.com/6632321/172258555-25837cb5-574d-4672-9e86-62ac35497d3e.png)
