### ISSUE TITLE
Doesn't work in VS Code

### ISSUE THREAD

**Issue by Muhammad-Jafar** [mathiasfrohlich/vscode-kotlin#56]
thank you for reading this issue before, am tried to installing this extension on my VS Code. It's done properly. But, when am try to running my code. vs code said : You don't have an extension for debugging Kotlin. Should we ..... ?

what I suppose to do with that ? there is any more guide for me to solve this ?
![image](https://user-images.githubusercontent.com/57802779/170830646-73c9461f-0ea7-4cd8-845e-a751602dc479.png)

**Comment by nishtahir** [comment]
This plugin does not provide language server or debugging capabilities. This is ONLY a syntax highlighter. https://github.com/mathiasfrohlich/vscode-kotlin#features. For a plugin with those capabilities see https://github.com/fwcd/kotlin-language-server
