### ISSUE TITLE
No methods outline with this plugin

### ISSUE THREAD

**Issue by andreszs** [mathiasfrohlich/vscode-kotlin#57]
This plugin does not enable the **OUTLINE** view to list any methods, functions or variables whatsoever. Nothing at all is shown.

![image](https://user-images.githubusercontent.com/10298071/172155760-dc36a53a-9103-4df7-83c3-82a6e0fee7cf.png)

**Comment by nishtahir** [comment]
This is not a supported feature.
If you look at the [list of features](https://github.com/mathiasfrohlich/vscode-kotlin#features), outlines is not an included feature
