### ISSUE TITLE
Support for Kotlin code in Markdown documents

### ISSUE THREAD

**Issue by hastebrot** [mathiasfrohlich/vscode-kotlin#6]
Code blocks starting with `` ```kotlin`` are not highlighted in Markdown documents.

**Comment by hastebrot** [comment]
I investigated this further. The editor view does not highlight Kotlin code black in Markdown documents, the Markdown preview does.

**Comment by phauer** [comment]
I'd also really appreciate having my Kotlin code in Markdown code blocks beeing highlighted.

**Comment by nishtahir** [comment]
This should be resolved in db07ba3. I'll be included in the next release.
