### ISSUE TITLE
Reserved words

### ISSUE THREAD

**Issue by ice1000** [mathiasfrohlich/vscode-kotlin#9]
```kotlin
header
impl
```

See https://stackoverflow.com/questions/44217331/what-does-impl-mean-in-kotlin

**Comment by ice1000** [comment]
Now they're

```kotlin
expect
actual
```

**Comment by ice1000** [comment]
@Jonatino @nishtahir @francis36012 @mathiasfrohlich :smiley:

**Comment by nishtahir** [comment]
This should be pretty easy to update.
